#include "Simulation/sim_transport_uart.h"

#include <stddef.h>
#include <string.h>

#include "main.h"

/*
 * USART2 is generated by STM32CubeMX and defined in main.c.
 */
extern UART_HandleTypeDef huart2;

/*
 * USART2 receives one byte at a time using interrupt mode.
 */
static uint8_t sim_uart_rx_byte = 0U;

void SimTransportUart_Init(void)
{
    HAL_StatusTypeDef status;

    sim_uart_rx_byte = 0U;

    SimTransportUart_SendLine("SIM INTERFACE READY");

    status = HAL_UART_Receive_IT(
        &huart2,
        &sim_uart_rx_byte,
        1U
    );

    if (status == HAL_OK)
    {
        SimTransportUart_SendLine("UART RX ARMED");
    }
    else if (status == HAL_BUSY)
    {
        SimTransportUart_SendLine("UART RX BUSY");
    }
    else
    {
        SimTransportUart_SendLine("UART RX ERROR");
    }
}




void SimTransportUart_SendString(const char *message)
{
    if (message == NULL)
    {
        return;
    }

    (void)HAL_UART_Transmit(
        &huart2,
        (uint8_t *)message,
        (uint16_t)strlen(message),
        1000U
    );
}


void SimTransportUart_SendLine(const char *message)
{
    SimTransportUart_SendString(message);
    SimTransportUart_SendString("\r\n");
}


uint8_t SimTransportUart_GetReceivedByte(void)
{
    return sim_uart_rx_byte;
}


HAL_StatusTypeDef SimTransportUart_ReceiveNextByte(void)
{
    return HAL_UART_Receive_IT(
        &huart2,
        &sim_uart_rx_byte,
        1U
    );
}
