#include "RTOS/rtos_queues.h"

#include "cmsis_os2.h"

#include <stddef.h>

/*
 * Queue handle generated by CubeMX in freertos.c.
 */
extern osMessageQueueId_t canRxQueueHandle;


void RTOS_Queue_Init(void)
{
    /*
     * Queue creation is performed by CubeMX / MX_FREERTOS_Init().
     *
     * No additional initialization is required here.
     */
}


bool RTOS_Queue_PushCANRx(const can_message_t *message)
{
    osStatus_t status;

    if (message == NULL)
    {
        return false;
    }

    if (canRxQueueHandle == NULL)
    {
        return false;
    }

    /*
     * Timeout = 0 because this function can be called
     * from interrupt context.
     */
    status = osMessageQueuePut(
            canRxQueueHandle,
            message,
            0U,
            0U);

    return (status == osOK);
}


bool RTOS_Queue_PopCANRx(can_message_t *message)
{
    osStatus_t status;

    if (message == NULL)
    {
        return false;
    }

    if (canRxQueueHandle == NULL)
    {
        return false;
    }

    /*
     * Non-blocking queue read.
     */
    status = osMessageQueueGet(
            canRxQueueHandle,
            message,
            NULL,
            0U);

    return (status == osOK);
}
