#include "Drivers/ADC/adc_driver.h"
#include "main.h"

/*
 * ADC handle is generated by CubeMX in main.c.
 */
extern ADC_HandleTypeDef hadc1;

/*
 * ADC parameters.
 */
#define ADC_MAX_COUNTS          (4095UL)
#define ADC_REFERENCE_MV        (3300UL)

/*
 * Example external voltage divider:
 *
 * Battery ---- 33k ----+---- ADC
 *                     |
 *                    10k
 *                     |
 *                    GND
 *
 * Divider ratio:
 *
 * Vin = Vadc * (33k + 10k) / 10k
 *     = Vadc * 4.3
 *
 * We avoid floating point:
 *
 * Battery_mV = ADC_mV * 43 / 10
 */
#define BATTERY_DIVIDER_NUMERATOR     (43UL)
#define BATTERY_DIVIDER_DENOMINATOR   (10UL)

void ADC_Driver_Init(void)
{
    /*
     * ADC hardware initialization is performed by MX_ADC1_Init().
     */
}

bool ADC_Driver_ReadRaw(adc_channel_t channel,
                        uint16_t *raw_value)
{
    HAL_StatusTypeDef status;
    uint32_t adc_value;

    if (raw_value == NULL)
    {
        return false;
    }

    switch (channel)
    {
        case ADC_CH_BATTERY_VOLTAGE:

            status = HAL_ADC_Start(&hadc1);

            if (status != HAL_OK)
            {
                return false;
            }

            status = HAL_ADC_PollForConversion(&hadc1, 10U);

            if (status != HAL_OK)
            {
                HAL_ADC_Stop(&hadc1);
                return false;
            }

            adc_value = HAL_ADC_GetValue(&hadc1);

            (void)HAL_ADC_Stop(&hadc1);

            if (adc_value > ADC_MAX_COUNTS)
            {
                return false;
            }

            *raw_value = (uint16_t)adc_value;

            return true;

        default:

            return false;
    }
}

bool ADC_Driver_ReadBatteryMv(uint16_t *battery_mv)
{
    uint16_t raw_value;
    uint32_t adc_mv;
    uint32_t calculated_battery_mv;

    if (battery_mv == NULL)
    {
        return false;
    }

    if (ADC_Driver_ReadRaw(ADC_CH_BATTERY_VOLTAGE,
                           &raw_value) == false)
    {
        return false;
    }

    adc_mv =
        ((uint32_t)raw_value * ADC_REFERENCE_MV) /
        ADC_MAX_COUNTS;

    calculated_battery_mv =
        (adc_mv * BATTERY_DIVIDER_NUMERATOR) /
        BATTERY_DIVIDER_DENOMINATOR;

    *battery_mv = (uint16_t)calculated_battery_mv;

    return true;
}